{
  "formatVersion": "0.3",
  "component": {
    "url": "../../library/1.0/library-1.0.module",
    "group": "test",
    "module": "library",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "4.8-20180417000132+0000",
      "buildId": "pouqkiul2rgyzl2vr7gnwdeumu"
    }
  },
  "variants": [
    {
      "name": "releaseLink",
      "attributes": {
        "org.gradle.native.debuggable": true,
        "org.gradle.native.kotlin.platform": "macos_x64",
        "org.gradle.native.optimized": true,
        "org.gradle.usage": "kotlin-native-klib"
      },
      "files": [
        {
          "name": "library.klib",
          "url": "library_release-1.0.klib",
          "size": 6803,
          "sha1": "681b1d8fd90b29b6cc04e2c4c629684517170ddf",
          "md5": "c6d5ac228e79062e1ab1767c40d7d0af"
        }
      ]
    }
  ]
}
